default:
  interruptible: true

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .cache/pip
    - venv/
    - ext/
    - ext_bin/

stages:
  - Build
  - Static Analysis
  - Run
  - Test

include:
  - local: .gitlab/MCAC.yml
  - local: .gitlab/static.yml
  - local: .gitlab/tests.yml
