default:
  image: python:3.9-slim-buster
  interruptible: true

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

#before_script:
#  - apk add --upgrade --no-cache
#    make cmake extra-cmake-modules g++ git
#    hdf5-dev mpfr-dev gmp-dev boost-dev libunwind-dev tiff-dev
#    python3 python3-dev py3-numpy-dev openblas-dev lapack-dev libxml2-dev libxslt-dev

before_script:
  - apt update
  - apt-get install -y
    make cmake extra-cmake-modules g++ git
    libhdf5-dev libmpfr-dev libgmp-dev libboost-dev libunwind-dev libtiff-dev
    python3 python3-dev libopenblas-dev liblapack-dev libxml2-dev libxslt1-dev

cache:
  paths:
    - .cache/pip
    - venv/
    - ext/
    - ext_bin/

stages:
  - Build
  - Static Analysis
  - Test


include:
  - local: .gitlab/MCAC.yml
  - local: .gitlab/pyMCAC.yml
