default:
  image: alpine:3.12
  interruptible: true

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# bash openssh curl ca-certificates libgomp libgcc libquadmath musl libgfortran
# openssl less wget rsync build-base libpng-dev
# freetype-dev libexecinfo-dev 

before_script:
  - apk add --upgrade --no-cache
    make cmake extra-cmake-modules g++ git
    hdf5-dev mpfr-dev gmp-dev boost-dev libunwind-dev
    python3 python3-dev openblas-dev lapack-dev libxml2-dev libxslt-dev

cache:
  paths:
    - .cache/pip
    - venv/
    - ext/
    - ext-bin/

stages:
  - Build
  - Static Analysis
  - Test


include:
  - local: .gitlab/MCAC.yml
  - local: .gitlab/pyMCAC.yml
