default:
  image: alpine3.12
  interruptible: true

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# bash openssh curl ca-certificates libgomp libgcc libquadmath musl libgfortran
# openssl less g++ make wget rsync build-base libpng-dev
# freetype-dev libexecinfo-dev 

before_script:
  - apk add --upgrade --no-cache openblas-dev lapack-dev
    hdf5-dev mpfr-dev gmp-dev boost-dev cmake extra-cmake-modules cmake-extras
    python3 libxml2-dev libxslt-dev

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - Build
  - Static Analysis
  - Test


include:
  - local: .gitlab/MCAC.yml
  - local: .gitlab/pyMCAC.yml
