---
#default_language_version:
#    python: python3.8
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: check-ast
          - id: check-builtin-literals
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
          - id: black-jupyter
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            name: isort (python)
          - id: isort
            name: isort (cython)
            types: [cython]
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.31.1
      hooks:
          - id: pyupgrade
            args: [--py38-plus]
    - repo: https://github.com/pycqa/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            entry: pflake8
            additional_dependencies: [pyproject-flake8, flake8-copyright]
    - repo: https://github.com/myint/docformatter
      rev: v1.4
      hooks:
          - id: docformatter
            args: [--in-place]
    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.1.1
      hooks:
          - id: pydocstyle
            additional_dependencies: [toml]
            exclude: (?x)^( cmake-format.py )$
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.942
      hooks:
          - id: mypy
            exclude: (?x)^( cmake-format.py )$
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.1
      hooks:
          - id: yamlfmt
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-toml
          - id: check-vcs-permalinks
          - id: mixed-line-ending
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.13
      hooks:
          - id: remove-crlf
          - id: remove-tabs
    - repo: https://github.com/crate-ci/typos
      rev: v1.5.0
      hooks:
          - id: typos
            exclude: ^docs/
    - repo: https://github.com/cheshirekow/cmake-format-precommit
      rev: v0.6.13
      hooks:
          - id: cmake-format
            args:
                - --line-width=100
                - --tab-size=4
                - --max-pargs-hwrap=4
                - --dangle-parens=True
                - --command-case=lower
                - --keyword-case=upper
                - --autosort=True
          - id: cmake-lint
