######################################################################
# Automatically generated by qmake (2.01a) jeu. juin 15 11:32:32 2017
######################################################################

TEMPLATE = app
TARGET = analyse_DLCA
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp

QT       += core gui
QT       += widgets


RESOURCES += \
    mainwindow.qrc
